"""Initial migration

Revision ID: 30d39274a0f8
Revises: fb0879aedb3f
Create Date: 2023-09-07 18:11:38.309746

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '30d39274a0f8'
down_revision: Union[str, None] = 'fb0879aedb3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('room_quantity', sa.Integer(), nullable=False))
    op.drop_column('hotels', 'room_quantiy')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hotels', sa.Column('room_quantiy', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('hotels', 'room_quantity')
    # ### end Alembic commands ###
